services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: uniconnect
      POSTGRES_USER: uniconnect
      POSTGRES_PASSWORD: uniconnect
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://uniconnect:uniconnect@db:5432/uniconnect
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: http://localhost:8000/api
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
